# Generated by Django 5.0.7 on 2024-07-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('totalWord', models.IntegerField(default=0)),
                ('totalStudy', models.IntegerField(default=20)),
                ('wordReview', models.IntegerField(default=0)),
                ('easyWord', models.IntegerField(default=0)),
                ('mediumWord', models.IntegerField(default=0)),
                ('hardWord', models.IntegerField(default=0)),
                ('ratioEasyWord', models.IntegerField(default=0)),
                ('ratioMediumWord', models.IntegerField(default=0)),
                ('ratioHardWord', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adj', 'adj'), ('adv', 'adv'), ('pronoun', 'pronoun'), ('preposition', 'preposition'), ('conjunction', 'conjunction'), ('interjection', 'interjection')], default=None, max_length=15)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=None, max_length=2)),
                ('pronunciation', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('meanning', models.CharField(max_length=50)),
                ('example', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Hard', max_length=10)),
                ('memoryLevel', models.IntegerField(default=1)),
                ('deadlineReview', models.IntegerField(default=1)),
                ('new_word', models.BooleanField(default=True)),
                ('totalReview', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.listword')),
            ],
        ),
    ]
